- id: '1546440401747'
  alias: New Automation
  trigger:
  - below: '75'
    entity_id: sensor.489_climate_kingsbridge_target_temp
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Kingsbridge Temp set below 75
    service: notify.all
