# Add local resources

resources:
  - url: /local/custom_ui/thermostat-card.js?v=1
    type: module

title: HAL9000
views:
  - title: default_view
    icon: mdi:home-assistant
    badges:
      - device_tracker.daves_iphone
      - device_tracker.tatis_iphone
      - device_tracker.stella
      - device_tracker.fluffy
      #- device_tracker.maritzas_iphone
    cards:
      - type: entities
        title: Time
        show_header_toggle: true
        entities:
          - sensor.zulu_time
          - sensor.est_time
          - sensor.pst_time
      - type: weather-forecast
        entity: weather.dark_sky

  - title: climate
    icon: mdi:nest-thermostat
    cards:
      - type: custom:thermostat-card
        title: North Nest
        entity: climate.north_nest
        hvac:
          states:
            'Off': 'off'
            'Cooling': 'cool'
            'Heating': 'heat'
          attribute: operation_mode
        ambient_temperature: sensor.1545_climate_north_nest_ambient_temp
      - type: custom:thermostat-card
        title: South Nest
        entity: climate.south_nest
        hvac:
          states:
            'Off': 'off'
            'Cooling': 'cool'
            'Heating': 'heat'
          attribute: operation_mode
        ambient_temperature: sensor.1545_climate_south_nest_ambient_temp
      - type: custom:thermostat-card
        title: Kingsbridge Nest
        entity: climate.kingsbridge
        hvac:
          states:
            'Off': 'off'
            'Cooling': 'cool'
            'Heating': 'heat'
          attribute: operation_mode
        ambient_temperature: sensor.489_climate_kingsbridge_ambient_temp
        
  - title: weather
    icon: mdi:weather-cloudy
    cards:
      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=26.378&lon=-80.107&zoom=5&level=surface&overlay=wind&menu=&message=&marker=true&calendar=&pressure=&type=map&location=coordinates&detail=&detailLat=26.348&detailLon=-80.110&metricWind=default&metricTemp=default&radarRange=-1
        aspect_ratio: 100%
        
  - title: security
    icon: mdi:cctv
    cards:
      - type: picture-entity
        title: Front Door
        entity: camera.front_door
        camera_image: camera.front_door
        show_info: true
        tap_action: dialog
      - type: picture-entity
        title: Pool
        entity: camera.pool
        camera_image: camera.pool
        show_info: true
        tap_action: dialog
      - type: picture-entity
        title: DogCam
        entity: camera.dogcam
        camera_image: camera.dogcam
        show_info: true
        tap_action: dialog
      - type: picture-entity
        title: Park
        entity: camera.park
        camera_image: camera.park
        show_info: true
        tap_action: dialog
      - type: picture-entity
        title: Garage
        entity: camera.garage
        camera_image: camera.garage
        show_info: true
        tap_action: dialog        
